#!/usr/bin/env python3
"""Export token-table addresses and the Fer-de-Lance type from elite-data.asm."""

from pathlib import Path
import re


def read_layout(listing):
    layout = {}
    for name in ("TKN1", "RUPLA", "RUGAL", "RUTOK"):
        pattern = (
            rf"^\.{name}\r?\n"
            r"(?:\.[^\r\n]+\r?\n)*"
            r"[ \t]+([0-9A-Fa-f]{4})\b"
        )
        matches = re.findall(pattern, listing, re.MULTILINE)
        if len(matches) != 1:
            raise ValueError(f"Expected one {name} address, found {len(matches)}")
        layout[name] = int(matches[0], 16)

    if layout["TKN1"] != 0x0E00:
        raise ValueError("TKN1 moved away from the loader's $0E00 destination")
    count = layout["RUGAL"] - layout["RUPLA"]
    if not 0 < count <= 255:
        raise ValueError("RUPLA must contain 1 to 255 system numbers")
    if layout["RUTOK"] - layout["RUGAL"] != count:
        raise ValueError("RUPLA and RUGAL must contain the same number of entries")
    if not layout["TKN1"] < layout["RUPLA"] < layout["RUGAL"] < layout["RUTOK"] < 0x1D00:
        raise ValueError("Token tables must stay within the loader's token area")
    matches = re.findall(
        r"^FER_DE_LANCE_TYPE = &([0-9A-Fa-f]+)[ \t]*\r?$",
        listing, re.MULTILINE
    )
    if len(matches) != 1:
        raise ValueError("Expected one assembled FER_DE_LANCE_TYPE export")
    ship_type = int(matches[0], 16)
    if not 1 <= ship_type <= 255:
        raise ValueError("FER_DE_LANCE_TYPE must fit a non-zero ship-type byte")
    layout["FER_DE_LANCE_TYPE"] = ship_type
    return layout


def main():
    output = Path("3-assembled-output/elite-token-layout.asm")
    listing = Path("3-assembled-output/compile.txt").read_text(encoding="utf-8")
    layout = read_layout(listing)
    lines = [
        "; Generated by elite-token-layout.py from the current data build.",
        "; Do not edit: symbols follow the current token and ship-role tables.",
        "",
    ]
    lines.extend(f" {name} = ${address:04X}" for name, address in layout.items())
    output.write_text("\n".join(lines) + "\n", encoding="ascii")
    print("Token table layout: " + ", ".join(
        f"{name}=${address:04X}" for name, address in layout.items()
    ))


if __name__ == "__main__":
    main()
