#!/usr/bin/env python3
"""Export entry points and the game's RNG workspace for the media loaders."""

from pathlib import Path
import re


COMLOD_LOAD_ADDRESS = 0x4000
LOCODE_LOAD_ADDRESS = 0x1D00


def read_layout(listing):
    layout = {}
    for name in ("COMLOD_ENTRY", "GAME_ENTRY", "GAME_RAND"):
        matches = re.findall(
            rf"^{name} = &([0-9A-Fa-f]+)[ \t]*\r?$", listing, re.MULTILINE
        )
        if len(matches) != 1:
            raise ValueError(f"Expected one {name} export, found {len(matches)}")
        address = int(matches[0], 16)
        if not 0 <= address <= 0xFFFF:
            raise ValueError(f"{name} is outside the 6502 address space")
        layout[name] = address
    if not 2 <= layout["GAME_RAND"] <= 0xFC:
        raise ValueError("GAME_RAND must fit four bytes in zero page after the CPU port")
    return layout


def check_entry(binary, load_address, entry, name):
    offset = entry - load_address
    if not 0 <= offset < len(binary):
        raise ValueError(f"{name} is outside its assembled binary")
    # Both entry labels begin with CLD. Check the freshly assembled bytes,
    # before elite-checksum.py applies encryption or appends file padding.
    if binary[offset] != 0xD8:
        raise ValueError(f"{name} does not point to the entry's CLD instruction")


def main():
    output_dir = Path("3-assembled-output")
    listing = (output_dir / "compile.txt").read_text(encoding="utf-8")
    layout = read_layout(listing)
    # These load origins are fixed regions of the C64 game's memory map.
    check_entry((output_dir / "COMLOD.unprot.bin").read_bytes(),
                COMLOD_LOAD_ADDRESS, layout["COMLOD_ENTRY"], "COMLOD_ENTRY")
    check_entry((output_dir / "ELTA.bin").read_bytes(),
                LOCODE_LOAD_ADDRESS, layout["GAME_ENTRY"], "GAME_ENTRY")
    lines = [
        "; Generated by elite-loader-layout.py from the current assembly.",
        "; Do not edit: these symbols follow the assembled code and workspaces.",
        "",
    ]
    lines.extend(f" {name} = ${address:04X}" for name, address in layout.items())
    (output_dir / "elite-loader-layout.asm").write_text(
        "\n".join(lines) + "\n", encoding="ascii"
    )
    print("Loader layout: " + ", ".join(
        f"{name}=${address:04X}" for name, address in layout.items()
    ))


if __name__ == "__main__":
    main()
